name: dynamicmatrix
on: push
jobs:
  oss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: OSS License Auditor
        uses: digi-wolk/olaudit-action@v1
        with:
          path: .
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
