name: lint
on: push
jobs:
  oss:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - id: extract-branch
        name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: LicenseFinder
        uses: jmservera/license-finder-action@main
        with:
          permitted-licenses: MIT,Apache-2.0

      - name: Publish Licenses
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          junit_files: "license_finder_report.xml"
          check_name: License Finder

      # - name: Upload result to GitHub Code Scanning
      #   if: success() || failure()
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif
