name: lint
on: push
jobs:
  oss:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo apt install python-is-python3
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
      - run: |
          poetry install
          poetry run pip freeze > requirements.txt

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - run: gem install license_finder
      - id: license-check
        run: echo "licenses=$(poetry run license_finder --python-version=3 --prepare | head)" >> $GITHUB_OUTPUT
      - if: steps.license-check.conclusion == 'failure'
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.license-check.outputs.licenses }}
